services:
  telegram-scheduler:
    # Build Image จาก Dockerfile ในโฟลเดอร์ปัจจุบัน (.)
    build: .
    
    # ตั้งชื่อ container ให้จำง่าย
    container_name: telegram_bot_scheduler
    
    # ตั้งค่าให้ container เริ่มทำงานใหม่เสมอเมื่อ Docker หรือเครื่องดับแล้วเปิดใหม่
    restart: always
    
    # ตั้งค่า Timezone ให้เป็นเวลาประเทศไทย
    environment:
      - TZ=Asia/Bangkok
      
    # เชื่อมต่อ (Mount) โฟลเดอร์ภายนอกเข้ากับภายใน container
    volumes:
      - ./logs:/app/logs